[2022-10-11 00:44:51,471] [asyncio] [DEBUG] : Using selector: EpollSelector
[2022-10-11 00:45:02,452] [root] [INFO] : name=borris
[2022-10-11 00:45:02,453] [aiohttp.server] [ERROR] : Error handling request
Traceback (most recent call last):
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 180, in static_server
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 140, in add_user
    json = json.loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-10-11 00:45:02,456] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:45:02 +0000] "POST /api/users HTTP/1.1" 500 245 "-" "python-requests/2.28.1"
[2022-10-11 00:45:03,064] [aiohttp.server] [ERROR] : Error handling request
Traceback (most recent call last):
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 180, in static_server
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 150, in add_entry
    json = await request.json()
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_request.py", line 671, in json
    return loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-10-11 00:45:03,064] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:45:03 +0000] "POST /api/entries HTTP/1.1" 500 245 "-" "python-requests/2.28.1"
[2022-10-11 00:47:11,659] [root] [INFO] : name=barry
[2022-10-11 00:47:11,659] [aiohttp.server] [ERROR] : Error handling request
Traceback (most recent call last):
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 180, in static_server
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 140, in add_user
    json = json.loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-10-11 00:47:11,661] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:47:11 +0000] "POST /api/users HTTP/1.1" 500 245 "-" "python-requests/2.28.1"
[2022-10-11 00:47:12,272] [aiohttp.server] [ERROR] : Error handling request
Traceback (most recent call last):
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 180, in static_server
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 150, in add_entry
    json = await request.json()
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_request.py", line 671, in json
    return loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-10-11 00:47:12,274] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:47:12 +0000] "POST /api/entries HTTP/1.1" 500 245 "-" "python-requests/2.28.1"
[2022-10-11 00:49:00,826] [root] [INFO] : name=1
[2022-10-11 00:49:00,827] [aiohttp.server] [ERROR] : Error handling request
Traceback (most recent call last):
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 180, in static_server
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 140, in add_user
    json = json.loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-10-11 00:49:00,828] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:49:00 +0000] "POST /api/users HTTP/1.1" 500 245 "-" "python-requests/2.28.1"
[2022-10-11 00:49:10,892] [root] [INFO] : name=booo
[2022-10-11 00:49:10,892] [aiohttp.server] [ERROR] : Error handling request
Traceback (most recent call last):
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 180, in static_server
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 140, in add_user
    json = json.loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-10-11 00:49:10,892] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:49:10 +0000] "POST /api/users HTTP/1.1" 500 245 "-" "python-requests/2.28.1"
[2022-10-11 00:49:11,503] [aiohttp.server] [ERROR] : Error handling request
Traceback (most recent call last):
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 180, in static_server
    return await handler(request)
  File "/home/aj/code/school-work/reaction-speed-test/server/app.py", line 150, in add_entry
    json = await request.json()
  File "/home/aj/.local/lib/python3.10/site-packages/aiohttp/web_request.py", line 671, in json
    return loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-10-11 00:49:11,505] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:49:11 +0000] "POST /api/entries HTTP/1.1" 500 245 "-" "python-requests/2.28.1"
[2022-10-11 00:50:49,575] [root] [INFO] : {"name": "1"}
[2022-10-11 00:50:49,592] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:50:49 +0000] "POST /api/users HTTP/1.1" 201 169 "-" "python-requests/2.28.1"
[2022-10-11 00:50:50,218] [aiohttp.access] [INFO] : ::1 [10/Oct/2022:23:50:50 +0000] "POST /api/entries HTTP/1.1" 201 169 "-" "python-requests/2.28.1"
